module.exports = {
  WELCOME_EMAIL: 'WELCOME_EMAIL',
  NEW_FOLLOWER: 'NEW_FOLLOWER',
  ACCOUNT_VERIFICATION: 'ACCOUNT_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_RESET_CONFIRMATION: 'PASSWORD_RESET_CONFIRMATION'
};
